source 'https://rubygems.org'

gem 'sinatra', :git => 'git@github.com:sinatra/sinatra.git'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'activerecord'
gem 'rake'
gem 'thin'
gem 'shotgun'
gem 'rspec'
gem 'capybara'
gem 'database_cleaner'
gem 'require_all'
gem 'pry'
